-- ============================================================
-- AgileOps — Seed Data (optional)
-- This file is intentionally empty. Create projects, sprints,
-- team members, and roles from the app UI.
-- Run: npm run db:init (once) then use the UI to add data.
-- ============================================================

-- No seed rows. Add default roles if you want them available on fresh install:
-- INSERT INTO roles (name, sort_order) VALUES
--   ('Developer', 1), ('Product Manager', 2), ('Designer', 3), ('QA', 4), ('DevOps', 5)
-- ON CONFLICT (name) DO NOTHING;
